#   Copyright (c) European Space Agency, 2024.
#
#   This file is subject to the terms and conditions defined in file 'LICENCE.txt', which
#   is part of this source code package. No part of the package, including
#   this file, may be copied, modified, propagated, or distributed except according to
#   the terms contained in the file ‘LICENCE.txt’.
name: gaia-bhthree
channels:
  - conda-forge
dependencies:
  - python == 3.9
  - numpy == 1.24.3
  - pip == 23.1.2
  - kepmodel == 1.0.6
  - pandas == 2.0.2
  - matplotlib == 3.7.1
  - astroquery == 0.4.6
  - astropy == 5.0.6
  - pip:
    - pystrometry == 0.5.0